AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Task 1 of 3: Building the foundation - Security (KMS), Storage (DynamoDB),
  and Notifications (SNS, SQS).

Parameters:
  ProjectName:
    Type: String
    Default: PROJET-3
    Description: A name for your project, used to name all the resources.

Resources:
  # --- 1. The Master Key to lock everything ---
  KMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub "KMS key for ${ProjectName}"
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Allow administration of the key
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  # --- 2. The Database to store results ---
  FileMetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ProjectName}-FileMetadata"
      AttributeDefinitions:
        - AttributeName: fileId
          AttributeType: S
      KeySchema:
        - AttributeName: fileId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
        KMSMasterKeyId: !Ref KMSKey
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  # --- 3. The Notification Service ---
  ProcessingNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${ProjectName}-ProcessingNotifications"
      KmsMasterKeyId: !Ref KMSKey
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  # --- 4. The "Mailbox" for failed Lambda executions ---
  FailedExecutionsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${ProjectName}-FailedExecutionsQueue"
      KmsMasterKeyId: !Ref KMSKey
      Tags:
        - Key: Project
          Value: !Ref ProjectName

Outputs:
  KMSKeyArn:
    Description: ARN of the master KMS Key.
    Value: !GetAtt KMSKey.Arn
  DynamoDBTableName:
    Description: Name of the DynamoDB table.
    Value: !Ref FileMetadataTable
  SNSTopicArn:
    Description: ARN of the SNS topic. 
    Value: !Ref ProcessingNotificationTopic
  DeadLetterQueueArn:
    Description: ARN of the Dead Letter Queue.
    Value: !GetAtt FailedExecutionsQueue.Arn